---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karafka-consumer
  template:
    metadata:
      labels:
        app: karafka-consumer
    spec:
      containers:
        - name: karafka-consumer
          image: rat_pay_app:latest
          imagePullPolicy: Never
          workingDir: /rails
          command: ["/bin/sh", "-c"]
          args: ["exec bundle exec karafka server 2>&1"]
          envFrom:
            - configMapRef:
                name: rat-pay-config
            - secretRef:
                name: rails-secret-key
            - secretRef:
                name: database-password
