---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidekiq-worker
  template:
    metadata:
      labels:
        app: sidekiq-worker
    spec:
      containers:
        - name: sidekiq-worker
          image: rat_pay_app:latest
          imagePullPolicy: Never
          workingDir: /rails
          command: ["/bin/sh", "-c"]
          args: ["exec bundle exec sidekiq 2>&1"]
          envFrom:
            - configMapRef:
                name: rat-pay-config
            - secretRef:
                name: rails-secret-key
            - secretRef:
                name: database-password
